#!/bin/sh
set -e

if [ "$1" = configure ] && command -v udevadm >/dev/null 2>&1; then
  udevadm control --reload-rules || true
  udevadm trigger --subsystem-match=mpp_class --subsystem-match=misc --subsystem-match=dma_heap || true
fi

exit 0

