#!/bin/sh
set -e

if [ "$1" = remove ] || [ "$1" = purge ]; then
  if command -v systemctl >/dev/null 2>&1 && [ -d /run/systemd/system ]; then
    systemctl daemon-reload || true
    systemctl restart avahi-daemon.service || true
  fi
fi

exit 0
